#define NATHAN_M_PROJECT_NAME cxx_helper
#define CXX_HELPER_BEGIN_NAMESPACE namespace NATHAN_M_PROJECT_NAME{

#ifdef CXX_HELPER_BEGIN_NAMESPACE
#define CXX_HELPER_END_NAMESPACE }
#else
#define CXX_HELPER_BEGIN_NAMESPACE
#define CXX_HELPER_END_NAMESPACE
#endif //CXX_HELPER_BEGIN_NAMESPACE